### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by TheScientist1900** [ParitoshParmar/C3D-LSTM--PyTorch#2]
Can you give the link of the dataset?

**Comment by ParitoshParmar** [comment]
Hi @TheScientist1900 : Sorry for the late response. Please download AQA-7 dataset from the following page: http://rtis.oit.unlv.edu/datasets.html . Let me know if you have further questions.

**Comment by ParitoshParmar** [comment]
Hi @TheScientist1900 Closing this issue. Please reopen it if you have any further questions/issues.
